Ugugushka.WebUI/Components/CartButtonViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Ugugushka.WebUI.Code.Extensions;

namespace Ugugushka.WebUI.Components
{
    public class CartButtonViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke() 
            => View(HttpContext.Session?.GetCartFromSession());
    }
}

Ugugushka.WebUI/Controllers/AdminController.cs
using System;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Ugugushka.Common.Concretes;
using Ugugushka.Data.Models;
using Ugugushka.Domain.Code.Constants;
using Ugugushka.Domain.Code.Interfaces;
using Ugugushka.Domain.DtoModels;
using Ugugushka.WebUI.Code.Abstractions;
using Ugugushka.WebUI.Code.Constants;
using Ugugushka.WebUI.Code.Extensions;
using Ugugushka.WebUI.ViewModels;

namespace Ugugushka.WebUI.Controllers
{
    [Authorize(Roles = RoleDefaults.Admin)]
    public class AdminController : AbstractController
    {
        private const int ToysPageSize = 20;
        private const int OrdersPageSize = 20;
        private const int PartitionsPageSize = 20;
        private const int CategoriesPageSize = 20;

        private readonly IToyManager _toyManager;
        private readonly IPictureManager _pictureManager;
        private readonly IOrderManager _orderManager;
        private readonly IPartitionManager _partitionManager;
        private readonly ICategoryManager _categoryManager;

        public AdminController(
            IPartitionManager partitionManager, ICategoryManager categoryManager,
            IToyManager toyManager, IPictureManager pictureManager, 
            IOrderManager orderManager, IMapper mapper) : base(mapper)
        {
            _toyManager = toyManager;
            _pictureManager = pictureManager;
            _orderManager = orderManager;
            _partitionManager = partitionManager;
            _categoryManager = categoryManager;
        }

        public async Task<IActionResult> Toys([FromQuery] ToyFilterInfo toyFilter, [FromQuery] int page = 1) => 
            View(new AdminToysViewModel {
                PagedToys = await _toyManager.GetPagedFilteredAsync(toyFilter, new PageInfo {PageNumber = page, PageSize = ToysPageSize})
            });

        [HttpGet]
        public async Task<IActionResult> AddToy()
        {
            ViewBag.Title = PageNameDefaults.AddToy.WithDomain();
            ViewBag.ActionTitle = PageNameDefaults.AddToy;
            ViewBag.CategoriesList = new SelectList(await _categoryManager.GetAllAsync(), "Id", "Name", null, "Partition.Name");

            return View(new AddToyViewModel(_pictureManager.Cloudinary));
        }

        public async Task<IActionResult> EditToy(int id)
        {

            var toy = await _toyManager.GetByIdAsync(id);
            var model = Mapper.Map<AddToyViewModel>(toy);

            ViewBag.Title = PageNameDefaults.EditToy.WithDomain();
            ViewBag.ActionTitle = PageNameDefaults.EditToy;
            ViewBag.CategoriesList = new SelectList(await _categoryManager.GetAllAsync(), "Id", "Name", toy.CategoryId, "Partition.Name");

            model.Cloudinary = _pictureManager.Cloudinary;
            return View(nameof(AddToy), model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToy(AddToyViewModel model)
        {
            if (ModelState.IsValid)
            {
                var createdToy = await _toyManager.SaveAsync(Mapper.Map<AddToyViewModel, ToyUpdateDto>(model));

                TempData["message"] = $"{createdToy.Name} был(а) успешно сохранён(а)!";
                
                return RedirectToAction(nameof(Toys));
            }

            var actionName = model.Id == 0 ? PageNameDefaults.AddToy : PageNameDefaults.EditToy;
            ViewBag.Title = actionName.WithDomain();
            ViewBag.ActionTitle = actionName;
            ViewBag.CategoriesList = new SelectList(await _categoryManager.GetAllAsync(), "Id", "Name", 
                model.CategoryId == 0? null : model.CategoryId, "Partition.Name");
            model.Cloudinary = _pictureManager.Cloudinary;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var deletedToy = await _toyManager.DeleteAsync(id);

            TempData["message"] = $"{deletedToy.Name} был(а) успешно удален(а)!";
            
            return RedirectToAction(nameof(Toys));
        }

        public async Task<IActionResult> Orders([FromQuery] int page = 1)
        {
            return View(new AdminOrdersViewModel
            {
                PagedOrders = await _orderManager.GetFilteredPagedAsync(new OrderFilterInfo(),
                    new PageInfo {PageNumber = page, PageSize = OrdersPageSize})
            });
        }

        public async Task<IActionResult> OrderInfo([FromRoute] Guid id, string returnUrl)
            => View(new AdminOrderInfoViewModel
            {
                Order = await _orderManager.GetByIdEagerAsync(id),
                ReturnUrl = returnUrl
            });

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetOrderStatus(AdminSetOrderStatusViewModel model, string returnUrl)
        {
            await _orderManager.SetOrderStatusAsync(model.OrderId, model.Status);
            
            TempData["message"] = "Статус заказа успешно изменён!";

            return RedirectToAction(nameof(OrderInfo), new {Id = model.OrderId, ReturnUrl = returnUrl});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteOrder(Guid id)
        {
            await _orderManager.DeleteAsync(id);

            TempData["message"] = "Заказ успешно удалён!";

            return RedirectToAction(nameof(Orders));
        }

        public async Task<IActionResult> Partitions([FromQuery] int page = 1) =>
            View(new AdminPartitionsViewModel { 
                PagedPartitions = await _partitionManager.GetPagedAsync(new PageInfo { 
                    PageNumber = page, 
                    PageSize = PartitionsPageSize
                })
            });

        public IActionResult AddPartition()
        {
            ViewBag.Title = PageNameDefaults.AddPartition.WithDomain();
            ViewBag.ActionTitle = PageNameDefaults.AddPartition;

            return View(new AdminAddPartitionViewModel());
        }

        public async Task<IActionResult> UpdatePartition([FromRoute] int id)
        {
            ViewBag.Title = PageNameDefaults.EditPartition.WithDomain();
            ViewBag.ActionTitle = PageNameDefaults.EditPartition;

            return View(nameof(AddPartition), Mapper.Map<AdminAddPartitionViewModel>(await _partitionManager.GetByIdAsync(id)));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPartition(AdminAddPartitionViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _partitionManager.SaveAsync(Mapper.Map<PartitionDto>(model));

                TempData["message"] = $"Раздел \"{model.Name}\" успешно сохранён!";

                return RedirectToAction(nameof(Partitions));
            }

            var actionName = model.Id == 0 ? PageNameDefaults.AddPartition : PageNameDefaults.EditPartition;
            ViewBag.Title = actionName.WithDomain();
            ViewBag.ActionTitle = actionName;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePartition(int id)
        {
            var partition = await _partitionManager.DeleteAsync(id);

            TempData["message"] = $"Раздел \"{partition.Name}\" успешно удалён!";

            return RedirectToAction(nameof(Partitions));
        }

        public async Task<IActionResult> Categories([FromQuery] int page = 1) =>
            View(new AdminCategoriesViewModel { 
                PagedCategories = await _categoryManager.GetAllPagedAsync(new PageInfo { 
                    PageNumber = page,
                    PageSize = CategoriesPageSize
                })
            });

        public async Task<IActionResult> AddCategory()
        {
            ViewBag.Title = PageNameDefaults.AddCategory.WithDomain();
            ViewBag.ActionTitle = PageNameDefaults.AddCategory;
            ViewBag.PartitionsList = new SelectList(await _partitionManager.GetAllAsync(), "Id", "Name", null);

            return View(new AdminAddCategoryViewModel());
        }

        public async Task<IActionResult> UpdateCategory([FromRoute] int id)
        {
            var model = Mapper.Map<AdminAddCategoryViewModel>(await _categoryManager.GetByIdAsync(id));

            ViewBag.Title = PageNameDefaults.EditCategory.WithDomain();
            ViewBag.ActionTitle = PageNameDefaults.EditCategory;
            ViewBag.PartitionsList = new SelectList(await _partitionManager.GetAllAsync(), "Id", "Name", model.PartitionId);

            return View(nameof(AddCategory), model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCategory(AdminAddCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _categoryManager.SaveAsync(Mapper.Map<CategoryDto>(model));

                TempData["message"] = $"Категория \"{model.Name}\" успешно сохранена!";

                return RedirectToAction(nameof(Categories));
            }

            var actionName = model.Id == 0 ? PageNameDefaults.AddCategory : PageNameDefaults.EditCategory;
            ViewBag.Title = actionName.WithDomain();
            ViewBag.ActionTitle = actionName;
            ViewBag.PartitionsList = new SelectList(await _partitionManager.GetAllAsync(), "Id", "Name", model.PartitionId);
            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCategory(int id)
        {
            var category = await _categoryManager.DeleteAsync(id);

            TempData["message"] = $"Категория \"{category.Name}\" успешно удалена!";

Ugugushka.WebUI/Views/Shared/_Error.cshtml
@{
    ViewBag.Title = "Критическая ошибка";
}

<section id="not_found" class="d-flex flex-column justify-content-center align-items-center mt-5">
    <h1>Произошла критическая ошибка!</h1>
    <p>Если вы видите эту страницу, пожалуйста обратитесь к администратору.</p>
    @Html.ActionLink("Вернуться на главную", "Index", "Home")
</section>

Ugugushka.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html itemscope="" itemtype="http://schema.org/WebPage" lang="ru-BY">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width"/>
    
    <title>@ViewBag.Title</title>
    <meta name="description" content="@ViewBag.Description"/>
    <meta name="keywords" content="@ViewBag.KeyWords"/>

    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:wght@300;400;500;700;800;900&family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/css/bundle.min.css"/>
    @await RenderSectionAsync("Css", false)

</head>
<body>
<div class="wrapper">
    <header>
        <nav id="menu" class="d-flex flex-wrap">
            <div class="d-flex align-items-center container-xl p-0">
                <div class="d-none d-sm-flex col-1 col-md-4">
                    <img class="bar-logo" src="~/img/green_logo70x70.png" height="70" width="70" alt="Угугушка"/>
                    <div class="logo-header flex-column justify-content-center pl-3">
                        <span class="d-flex">Ugugushka.by</span>
                        <span class="d-flex">Интернет-магазин игрушек</span>
                    </div>
                </div>
                <div class="col-7 col-md-5">
                    <form class="search-block">
                        <input class="form-control search-input" type="text" placeholder="Поиск игрушек"/>
                        <button class="btn search-btn" type="submit"><i class="fas fa-search"></i></button>
                    </form>
                </div>
                <div class="icon-links d-flex align-items-center ml-auto">
                    @await Component.InvokeAsync("CartButton")
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <a class="btn btn-borderless d-flex" href="@Url.Action("Login", "Account")">
                            <i class="fas fa-user"></i>
                            <span class="bar-hide">Войти</span>
                        </a>
                    }
                    else
                    {
                        @using (Html.BeginForm("Logout", "Account", new {ReturnUrl = Context.Request.Path}, FormMethod.Post, true, new {@class = "d-flex"}))
                        {
                            <button class="btn btn-borderless d-flex" href="@Url.Action("Login", "Account")">
                                <i class="fas fa-sign-out-alt"></i>
                                <span class="bar-hide">Выйти</span>
                            </button>
                        }
                    }
                    <div onclick="showBar()" class="btn btn-borderless show-bar-btn">
                        <i class="fa fa-bars"></i>
                    </div>
                </div>
            </div>
            <div id="barItems" class="menu-links col-12">
                <div class="d-flex container-xl">
                    <a class="btn btn-borderless close" href="javascript:void(0)" onclick="showBar()"><i class="fas fa-times"></i></a>
                    <a href="@Url.Action("Index", "Home")"><i class="fas fa-home mr-3 mr-md-2"></i>Главная</a>
                    @await Component.InvokeAsync("CatalogButton")
                    <a href="@Url.Action("Contacts", "Home")"><i class="fas fa-map-marker-alt mr-3 mr-md-2"></i>Контакты</a>
                    @if (User.IsInRole(RoleDefaults.Admin))
                    {
                <div class="dropdown">
                    <button class="btn"><i class="fas fa-cog mr-3 mr-md-2"></i>Управление</button>
                    <div class="dropdown-content">
                        <a href="@Url.Action("Toys", "Admin")">Игрушки</a>
                        <a href="@Url.Action("Orders", "Admin")">Заказы</a>
                        <a href="@Url.Action("Partitions", "Admin")">Разделы</a>
                        <a href="@Url.Action("Categories", "Admin")">Категории</a>
                    </div>
                </div>
                        
                    }
                </div>
            </div>
            <div id="barBack" class="bar-back"></div>
        </nav>
        </header>

        <main class="container-lg container-xl">
            @RenderBody()
        </main>
    </div>

<footer class="d-flex justify-content-center align-items-center">
    <div class="d-flex">
        2020 &copy; Ugugushka.by &mdash; Интернет-магазин игрушек
    </div>
</footer>
<script type="text/javascript">
    function showBar(){
        const x = document.getElementById("barItems");
        const back = document.getElementById("barBack");
        if (x.className === "menu-links col-12") {
            x.className += " responsive";
            back.style = "display:block;";
        } else {
            x.className = "menu-links col-12";
            back.style = "display:none;";
        }
    }
</script>
@await RenderSectionAsync("PageScripts", false)
</body>
</html>