Ugugushka.WebUI/ViewModels/AddToyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using CloudinaryDotNet;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using Ugugushka.Domain.DtoModels;
using Ugugushka.WebUI.Code.Abstractions;

namespace Ugugushka.WebUI.ViewModels
{
    public class AddToyViewModel : AbstractCloudinaryModel
    {
        public AddToyViewModel() : base(null) { }
        public AddToyViewModel(Cloudinary cloudinary) : base(cloudinary) { }

        public int Id { get; set; }

        [DisplayName("Название")]
        [MaxLength(70, ErrorMessage = "Количество символов названия не должно превышать 70!")]
        [Required(ErrorMessage = "Вы должны ввести название!")]
        public string Name { get; set; }

        [DisplayName("Описание")]
        [MaxLength(500, ErrorMessage = "Количество символов описания не должно превышать 500!")]
        [Required(ErrorMessage = "Вы должны ввести описание")]
        public string Description { get; set; }

        [DisplayName("Категория")] 
        public int? CategoryId { get; set; }

        [DisplayName("Цена")]
        [Required(ErrorMessage = "Вы должны ввести цену!")]
        [DataType(DataType.Currency, ErrorMessage = "Некорректное значение")]
        [Range(0, Double.MaxValue, ErrorMessage = "Цена должна быть больше 0!")]
        public decimal Price { get; set; }

        [MinLength(1, ErrorMessage = "Нужно добавить как минимум 1 фотографию!")]
        [MaxLength(5, ErrorMessage = "Максимально возможное количество фотографий - 5!")]
        public List<ToyImageDto> Images { get; set; } = new List<ToyImageDto>();
    }
}

Ugugushka.WebUI/Components/OrderInfoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Ugugushka.Domain.DtoModels;

namespace Ugugushka.WebUI.Components
{
    public class OrderInfoViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(OrderDto order, bool withStatus)
        {
            ViewBag.IsOrderStatusVisible = withStatus;
            return View(order);
        }
    }
}

Ugugushka.WebUI/Controllers/AdminController.cs
using System;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Ugugushka.Common.Concretes;
using Ugugushka.Data.Models;
using Ugugushka.Domain.Code.Constants;
using Ugugushka.Domain.Code.Interfaces;
using Ugugushka.Domain.DtoModels;
using Ugugushka.WebUI.Code.Abstractions;
using Ugugushka.WebUI.Code.Constants;
using Ugugushka.WebUI.Code.Extensions;
using Ugugushka.WebUI.ViewModels;

namespace Ugugushka.WebUI.Controllers
{
    [Authorize(Roles = RoleDefaults.Admin)]
    public class AdminController : AbstractController
    {
        private const int ToysPageSize = 20;
        private const int OrdersPageSize = 20;
        private const int PartitionsPageSize = 20;
        private const int CategoriesPageSize = 20;

        private readonly IToyManager _toyManager;
        private readonly IPictureManager _pictureManager;
        private readonly IOrderManager _orderManager;
        private readonly IPartitionManager _partitionManager;
        private readonly ICategoryManager _categoryManager;

        public AdminController(
            IPartitionManager partitionManager, ICategoryManager categoryManager,
            IToyManager toyManager, IPictureManager pictureManager, 
            IOrderManager orderManager, IMapper mapper) : base(mapper)
        {
            _toyManager = toyManager;
            _pictureManager = pictureManager;
            _orderManager = orderManager;
            _partitionManager = partitionManager;
            _categoryManager = categoryManager;
        }

        public async Task<IActionResult> Toys([FromQuery] ToyFilterInfo toyFilter, [FromQuery] int page = 1) => 
            View(new AdminToysViewModel {
                PagedToys = await _toyManager.GetPagedFilteredAsync(toyFilter, new PageInfo {PageNumber = page, PageSize = ToysPageSize})
            });

        [HttpGet]
        public async Task<IActionResult> AddToy()
        {
            ViewBag.Title = PageNameDefaults.AddToy.WithDomain();
            ViewBag.ActionTitle = PageNameDefaults.AddToy;
            ViewBag.CategoriesList = new SelectList(await _categoryManager.GetAllAsync(), "Id", "Name", null, "Partition.Name");

            return View(new AddToyViewModel(_pictureManager.Cloudinary));
        }

        public async Task<IActionResult> EditToy(int id)
        {

            var toy = await _toyManager.GetByIdAsync(id);
            var model = Mapper.Map<AddToyViewModel>(toy);

            ViewBag.Title = PageNameDefaults.EditToy.WithDomain();
            ViewBag.ActionTitle = PageNameDefaults.EditToy;
            ViewBag.CategoriesList = new SelectList(await _categoryManager.GetAllAsync(), "Id", "Name", toy.CategoryId, "Partition.Name");

            model.Cloudinary = _pictureManager.Cloudinary;
            return View(nameof(AddToy), model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToy(AddToyViewModel model)
        {
            if (ModelState.IsValid)
            {
                var createdToy = await _toyManager.SaveAsync(Mapper.Map<AddToyViewModel, ToyUpdateDto>(model));

                TempData["message"] = $"{createdToy.Name} был(а) успешно сохранён(а)!";
                
                return RedirectToAction(nameof(Toys));
            }

            var actionName = model.Id == 0 ? PageNameDefaults.AddToy : PageNameDefaults.EditToy;
            ViewBag.Title = actionName.WithDomain();
            ViewBag.ActionTitle = actionName;
            ViewBag.CategoriesList = new SelectList(await _categoryManager.GetAllAsync(), "Id", "Name", 
                model.CategoryId == 0? null : model.CategoryId, "Partition.Name");
            model.Cloudinary = _pictureManager.Cloudinary;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var deletedToy = await _toyManager.DeleteAsync(id);

            TempData["message"] = $"{deletedToy.Name} был(а) успешно удален(а)!";
            
            return RedirectToAction(nameof(Toys));
        }

        public async Task<IActionResult> Orders([FromQuery] int page = 1)
        {
            return View(new AdminOrdersViewModel
            {
                PagedOrders = await _orderManager.GetFilteredPagedAsync(new OrderFilterInfo(),
                    new PageInfo {PageNumber = page, PageSize = OrdersPageSize})
            });
        }

        public async Task<IActionResult> OrderInfo([FromRoute] Guid id, string returnUrl)
            => View(new AdminOrderInfoViewModel
            {
                Order = await _orderManager.GetByIdEagerAsync(id),
                ReturnUrl = returnUrl
            });

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SetOrderStatus(AdminSetOrderStatusViewModel model, string returnUrl)
        {
            await _orderManager.SetOrderStatusAsync(model.OrderId, model.Status);
            
            TempData["message"] = "Статус заказа успешно изменён!";

            return RedirectToAction(nameof(OrderInfo), new {Id = model.OrderId, ReturnUrl = returnUrl});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteOrder(Guid id)
        {
            await _orderManager.DeleteAsync(id);

            TempData["message"] = "Заказ успешно удалён!";

            return RedirectToAction(nameof(Orders));
        }

        public async Task<IActionResult> Partitions([FromQuery] int page = 1) =>
            View(new AdminPartitionsViewModel { 
                PagedPartitions = await _partitionManager.GetPagedAsync(new PageInfo { 
                    PageNumber = page, 
                    PageSize = PartitionsPageSize
                })
            });

        public IActionResult AddPartition()
        {
            ViewBag.Title = PageNameDefaults.AddPartition.WithDomain();
            ViewBag.ActionTitle = PageNameDefaults.AddPartition;

            return View(new AdminAddPartitionViewModel());
        }

        public async Task<IActionResult> UpdatePartition([FromRoute] int id)
        {
            ViewBag.Title = PageNameDefaults.EditPartition.WithDomain();
            ViewBag.ActionTitle = PageNameDefaults.EditPartition;

            return View(nameof(AddPartition), Mapper.Map<AdminAddPartitionViewModel>(await _partitionManager.GetByIdAsync(id)));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPartition(AdminAddPartitionViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _partitionManager.SaveAsync(Mapper.Map<PartitionDto>(model));

                TempData["message"] = $"Раздел \"{model.Name}\" успешно сохранён!";

                return RedirectToAction(nameof(Partitions));
            }

            var actionName = model.Id == 0 ? PageNameDefaults.AddPartition : PageNameDefaults.EditPartition;
            ViewBag.Title = actionName.WithDomain();
            ViewBag.ActionTitle = actionName;

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePartition(int id)
        {
            var partition = await _partitionManager.DeleteAsync(id);

            TempData["message"] = $"Раздел \"{partition.Name}\" успешно удалён!";

            return RedirectToAction(nameof(Partitions));
        }

        public async Task<IActionResult> Categories([FromQuery] int page = 1) =>
            View(new AdminCategoriesViewModel { 
                PagedCategories = await _categoryManager.GetAllPagedAsync(new PageInfo { 
                    PageNumber = page,
                    PageSize = CategoriesPageSize
                })
            });

        public async Task<IActionResult> AddCategory()
        {
            ViewBag.Title = PageNameDefaults.AddCategory.WithDomain();
            ViewBag.ActionTitle = PageNameDefaults.AddCategory;
            ViewBag.PartitionsList = new SelectList(await _partitionManager.GetAllAsync(), "Id", "Name", null);

            return View(new AdminAddCategoryViewModel());
        }

        public async Task<IActionResult> UpdateCategory([FromRoute] int id)
        {
            var model = Mapper.Map<AdminAddCategoryViewModel>(await _categoryManager.GetByIdAsync(id));

            ViewBag.Title = PageNameDefaults.EditCategory.WithDomain();
            ViewBag.ActionTitle = PageNameDefaults.EditCategory;
            ViewBag.PartitionsList = new SelectList(await _partitionManager.GetAllAsync(), "Id", "Name", model.PartitionId);

            return View(nameof(AddCategory), model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCategory(AdminAddCategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                await _categoryManager.SaveAsync(Mapper.Map<CategoryDto>(model));

                TempData["message"] = $"Категория \"{model.Name}\" успешно сохранена!";

                return RedirectToAction(nameof(Categories));
            }

            var actionName = model.Id == 0 ? PageNameDefaults.AddCategory : PageNameDefaults.EditCategory;
            ViewBag.Title = actionName.WithDomain();
            ViewBag.ActionTitle = actionName;
            ViewBag.PartitionsList = new SelectList(await _partitionManager.GetAllAsync(), "Id", "Name", model.PartitionId);
            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCategory(int id)
        {
            var category = await _categoryManager.DeleteAsync(id);

            TempData["message"] = $"Категория \"{category.Name}\" успешно удалена!";

Ugugushka.WebUI/Controllers/ImageController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Ugugushka.Domain.Code.Constants;
using Ugugushka.Domain.Code.Interfaces;

namespace Ugugushka.WebUI.Controllers
{
    [Authorize(Roles = RoleDefaults.Admin)]
    [ApiController]
    [Route("api/[controller]")]
    public class ImageController : Controller
    {
        private readonly IPictureManager _pictureManager;
        public ImageController(IPictureManager pictureManager)
        {
            _pictureManager = pictureManager;
        }

        [HttpPost]
        public async Task<IActionResult> UploadImages(IFormFileCollection images)
        {
            if (images == null)
                return BadRequest();

            return Ok(await _pictureManager.UploadPicturesAsync(images));
        }
    }
}

Ugugushka.WebUI/Controllers/ToyController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Ugugushka.Common.Concretes;
using Ugugushka.Domain.Code.Constants;
using Ugugushka.Domain.Code.Extensions;
using Ugugushka.Domain.Code.Interfaces;
using Ugugushka.Domain.DtoModels;
using Ugugushka.WebUI.Code.Abstractions;
using Ugugushka.WebUI.ViewModels;

namespace Ugugushka.WebUI.Controllers
{
    [Authorize]
    public class ToyController : AbstractController
    {
        private const int ToysPageSize = 10;

        private readonly IToyManager _toyManager;
        private readonly IPictureManager _pictureManager;

        public ToyController(IToyManager toyManager, IPictureManager pictureManager, IMapper mapper) : base(mapper)
        {
            _pictureManager = pictureManager;
            _toyManager = toyManager;
        }

        public async Task<IActionResult> Toys([FromQuery] ToyFilterInfo toyFilter, [FromRoute] int page = 1)
        {
            return View(
                (await _toyManager.GetPagedFilteredAsync(toyFilter,
                    new PageInfo {PageNumber = page, PageSize = ToysPageSize})).Map<ToyDto, ToyItemViewModel>(Mapper));
        }

        [HttpGet]
        [Authorize(Roles = RoleDefaults.Admin)]
        public IActionResult AddToy() =>
            View(new AddToyViewModel(_pictureManager.Cloudinary));

        [HttpPost]
        [Authorize(Roles = RoleDefaults.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToy(AddToyViewModel toy)
        {
            if (ModelState.IsValid)
            {
                var createdToy = await _toyManager.CreateAsync(Mapper.Map<AddToyViewModel, ToyCreateDto>(toy));
                
                await _pictureManager.ChangePictureTagAsync(
                    createdToy.Images.Select(x => x.PublicId).ToList(),
                    CloudinaryTagDefaults.Toy);
                await _pictureManager.DeleteTemporaryPicturesAsync();
                
                TempData["message"] = $"{toy.Name} has been saved";
                return RedirectToAction("Toys");
            }
            else
            {
                toy.Cloudinary = _pictureManager.Cloudinary;
                return View(toy);
            }
        }

        public async Task<IActionResult> ToyInfo([FromRoute] int id) =>
            View(new ToyInfoViewModel(_pictureManager.Cloudinary) {Toy = await _toyManager.GetByIdAsync(id)});

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _toyManager.DeleteAsync(id);

            return RedirectToAction("Toys");
        }
    }
}

Ugugushka.WebUI/Views/Admin/AddCategory.cshtml
@model AdminAddCategoryViewModel


<section class="card my-5">
        <div class="card-header">
            <h1>@ViewBag.ActionTitle</h1>
        </div>
    @using (Html.BeginForm("AddCategory", "Admin", new { }, FormMethod.Post, true, new { }))
    {
            @Html.HiddenFor(x => x.Id)
            <div class="form-group">
                @Html.LabelFor(x => x.Name, null, new { @class = "d-block mb-3" })
                @Html.TextBoxFor(x => x.Name, null, new { @class = "form-control text-input" })
                @Html.ValidationMessageFor(x => x.Name)
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.PartitionId, null, new { @class = "d-block mb-3" })
                <div class="select-wrapper">
                    @Html.DropDownListFor(x => x.PartitionId, ViewBag.PartitionsList as SelectList, "Не выбран", new { @class = "form-control primary-select" })
                </div>
                @Html.ValidationMessageFor(x => x.PartitionId)
            </div>
            <input type="submit" class="btn btn-turquoise mr-2" value="Сохранить" />
            @Html.ActionLink("Назад", "Categories", null, htmlAttributes: new { @class = "btn btn-secondary" })
    }
</section>

Ugugushka.WebUI/Views/Admin/AddPartition.cshtml
@model AdminAddPartitionViewModel

<section class="card my-5">
    <div class="card-header">
        <h1>@ViewBag.ActionTitle</h1>
    </div>
    @using (Html.BeginForm("AddPartition", "Admin", new { }, FormMethod.Post, true, new { }))
    {
        @Html.HiddenFor(x => x.Id)
        <div class="form-group">
            @Html.LabelFor(x => x.Name, null, new { @class = "d-block mb-3"})
            @Html.TextBoxFor(x => x.Name, null, new { @class = "form-control text-input"})
            @Html.ValidationMessageFor(x => x.Name)
        </div>
        <input type="submit" class="btn btn-turquoise mr-2" value="Сохранить"/>
        @Html.ActionLink("Назад", "Partitions", null, htmlAttributes: new { @class = "btn btn-secondary" })
    }
</section>

Ugugushka.WebUI/Views/Admin/AddToy.cshtml
@model AddToyViewModel

<section class="card my-5">
    <div class="card-header">
        <h1>@ViewBag.ActionTitle</h1>
    </div>
    @using (Html.BeginForm("AddToy", "Admin", FormMethod.Post, htmlAttributes: new { @enctype = "multipart/form-data", @id = "form" }))
    {
        @Html.HiddenFor(x => x.Id)
        @foreach (var property in ViewData.ModelMetadata.Properties)
        {
            switch (property.PropertyName)
            {
                case "Id":
                case "Images":
                case "Cloudinary":
                    break;
                case "CategoryId":
                    <div class="form-group">
                        @Html.LabelFor(x => x.CategoryId, null, new { @class = "d-block mb-3" })
                        <div class="select-wrapper">
                            @Html.DropDownListFor(x => x.CategoryId, ViewBag.CategoriesList as SelectList, "Нет категории", new { @class = "form-control primary-select" })
                        </div>
                        @Html.ValidationMessageFor(x => x.CategoryId)
                    </div>
                    break;
                default:
                    <div class="form-group">
                    <label class="d-block mb-3" for="@property.PropertyName">@(property.DisplayName ?? property.PropertyName)</label>
                    @if (property.PropertyName == "Description")
                    {
                        @Html.TextArea(property.PropertyName, null, new { rows = 5, @class = "form-control text-input", @placeholder = property.DisplayName })
                    }
                    else if (property.PropertyName == "IsOnStock")
                    {
                        @Html.CheckBox(property.PropertyName)
                    }
                    else
                    {
                        @Html.TextBox(property.PropertyName, null, htmlAttributes: new { @class = "form-control text-input", @placeholder = property.DisplayName })
                    }
                    @Html.ValidationMessage(property.PropertyName)
                </div>
                    break;
            }
        }

        <div class="form-group">
            <label class="d-block mb-3">Фотографии</label>
            <div class="d-flex align-items-center">
                <div class="d-flex" id="images"></div>
                <label id="upload_btn" class="d-flex btn-upload-img" for="image">
                    <div id="plus_icon" class="d-flex upload-icon justify-content-center align-items-center">
                        <i class="fas fa-plus"></i>
                    </div>
                    <div id="loader" class="loader" style="display: none;"></div>
                </label>
                <input hidden type="file" name="image" id="image" accept="image/png, image/jpeg" multiple/>
            </div>
            <div id="upload_error_block" class="field-validation-error" style="display: none;"></div>
            @Html.ValidationMessageFor(x => x.Images)
        </div>

        <input type="submit" class="btn btn-turquoise mr-2" value="Сохранить" />
        @Html.ActionLink("Назад", "Toys", null, htmlAttributes: new { @class = "btn btn-secondary" })

        <div id="img_data"></div>
    }
</section>

@section PageScripts
{
    <script src="~/libs/jquery/jquery.min.js" type="text/javascript"></script>
    <script src="~/libs/jquery-validate/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/libs/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script>
        // Razor JS variables initialization
        const cloudPath = '@Model.Cloudinary.Api.UrlImgUp.Secure().BuildUrl()';
        var imgArray = [
            @foreach (var img in Model.Images.OrderByDescending(x => x.IsMain))
            {
                @: { publicId: '@img.PublicId', format: '@img.Format' },
            }
        ];
        var isUploadBtnHided = false;

        // DOM Elements
        const imgInputBlock = $('#img_data');
        const imgBlock = $("#images");
        const loader = $("#loader");
        const plusIcon = $("#plus_icon");
        const uploadBtn = $("#upload_btn");
        const uploadErrorBlock = $('#upload_error_block');

        $(document).ready(function() {
            updateImageArray();
            updateInputArray();
        });

        $("#image").on("change",
            function(e) {
                uploadImage();
            });

        function toggleUploading() {
            loader.toggle();
            loader.toggleClass('d-flex');
            plusIcon.toggle();
            plusIcon.toggleClass('d-flex');
        }

        function updateUploadBtn() {
            if (imgArray.length === 5 && !isUploadBtnHided) {
                uploadBtn.toggleClass('d-flex');
                uploadBtn.toggleClass('collapse');
                isUploadBtnHided = !isUploadBtnHided;
            } else if (imgArray.length < 5 && isUploadBtnHided) {
                uploadBtn.toggleClass('d-flex');
                uploadBtn.toggleClass('collapse');
                isUploadBtnHided = !isUploadBtnHided;
            }
        }

        function updateInputArray() {
            // Update input array
            imgInputBlock.html('');
            imgArray.forEach(function(item, index) {
                appendImageInput(item.publicId, item.format, index);
            });
        }

        function updateImageArray() {
            imgBlock.html('');
            imgArray.forEach(function(item, index) {
                appendImage(item.publicId, item.format, index);
            });
        }

        function appendImage(publicId, format, index) {
            const div = $("<div class='img-preview'></div>")
                .attr('data-index', index);
            $("<img class='d-flex mr-2' height='130' width='130'/>")
                .attr('src', `${cloudPath}/${publicId}.${format}`)
                .appendTo(div);
            $("<div class='img-menu'></div>")
                .append($("<i class='btn btn-secondary fas fa-arrow-left'></i>")
                    .on('click', onMoveImgLeft))
                .append($("<i class='btn btn-secondary fas fa-arrow-right'></i>")
                    .on('click', onMoveImgRight))
                .append($("<i class='btn btn-secondary fas fa-times'></i>")
                    .on('click', onDeleteImage))
                .appendTo(div);
            div.appendTo(imgBlock);
        }

        function onMoveImgLeft(e) {
            const elA = e.target.parentNode.parentNode;
            const index = parseInt(elA.dataset.index);
            const elB = $(`div.img-preview[data-index=${index - 1}]`)[0];

            if (!elB) return;

            elA.dataset.index = index - 1;
            elB.dataset.index = index;

            swapAImages(index, index - 1);
            elA.parentNode.insertBefore(elA, elB);
            updateInputArray();
        }

        function onMoveImgRight(e) {
            const elA = e.target.parentNode.parentNode;
            const index = parseInt(elA.dataset.index);
            console.log(index);
            const elB = $(`div.img-preview[data-index=${index + 1}]`)[0];

            if (!elB) return;

            elA.dataset.index = index + 1;
            elB.dataset.index = index;

            swapAImages(index, index + 1);
            elA.parentNode.insertBefore(elB, elA);
            updateInputArray();
        }

        function appendImageInput(publicId, format, index) {
            $(`<input type='hidden' name='Images[${index}].Format' id='Images[${index}]_Format'/>`)
                .val(format)
                .appendTo(imgInputBlock);
            $(`<input type='hidden' name='Images[${index}].PublicId' id='Images[${index}]_PublicId'/>`)
                .val(publicId)
                .appendTo(imgInputBlock);
        }

        function swapAImages(i, j) {
            const t = imgArray[i];
            imgArray[i] = imgArray[j];
            imgArray[j] = t;
        }

        function onDeleteImage(e) {
            const div = e.target.parentNode.parentNode;
            const i = div.dataset.index;

            div.remove();
            imgArray.splice(i, 1);
            updateInputArray();
            updateImageArray();
            updateUploadBtn();
        }

        function onUploadError(msg) {
            toggleUploading();
            uploadErrorBlock.toggle(true);
            uploadErrorBlock.text(msg);
        }

        function uploadImage() {
            const files = $("#image")[0].files;

            if (!files) return;

            toggleUploading();

            if (files.length > 5 - imgArray.length) {
                onUploadError('Максимально возможное количество фотографий - 5!');
                return;
            }

            const form = new FormData();
            for (let i = 0; i < files.length; i++) {
                form.append('images', files[i]);
                console.log('images', files[i]);
            }

            fetch('@Url.Action("UploadImages", "Image")',
                    {
                        method: 'POST',
                        body: form
                    })
                .then(r => {
                    if (r.ok) {
                        r.json().then(imgArr => {
                            imgArr.forEach(function(img) {
                                appendImage(img.publicId, img.format, imgArray.length);
                                appendImageInput(img.publicId, img.format, imgArray.length);
                                imgArray.push({ publicId: img.publicId, format: img.format });
                            });

                            toggleUploading();
                            updateUploadBtn();
                            uploadErrorBlock.toggle(false);
                        });
                    } else {
                        onUploadError(r.error);
                    }
                }).catch(onUploadError);
        }
    </script>
}

Ugugushka.WebUI/Views/Admin/OrderInfo.cshtml
@using Ugugushka.Common.Concretes
@model AdminOrderInfoViewModel

@{
    ViewBag.Title = PageNameDefaults.OrderInfo.WithDomain();
}

<section class="card mt-5">
    <section class="card-header d-flex align-items-center">
        <div class="col-6">
            <h1>@PageNameDefaults.OrderInfo</h1>
        </div>
        <div class="ml-auto">
            <a class="btn btn-secondary" href="@Model.ReturnUrl">Назад</a>
        </div>
    </section>
    @if (TempData["message"] != null)
    {
        <div class="d-flex mb-3 alert alert-success">
            @TempData["message"]
        </div>
    }

    @await Component.InvokeAsync("OrderInfo", new { order = Model.Order, withStatus = true })

    <section class="d-flex justify-content-center">
        @using (Html.BeginForm("DeleteOrder", "Admin", new { }, FormMethod.Post, true, new { @class = "d-flex" }))
        {
            @Html.Hidden("Id", Model.Order.Id)
            <input class="btn btn-secondary mx-2" type="submit" value="Удалить" />
        }
        
        @if ((int)Model.Order.Status == 0)
        {
            @using (Html.BeginForm("SetOrderStatus", "Admin", new {Model.ReturnUrl}, FormMethod.Post, true, new {@class = "d-flex"}))
            {
                @Html.Hidden("OrderId", Model.Order.Id)
                @Html.Hidden("Status", OrderStatus.InProcess)
                <input class="btn btn-secondary mx-2" type="submit" value="Отметить как принятый"/>
            }
        }
        @if ((int)Model.Order.Status == 1)
        {
            @using (Html.BeginForm("SetOrderStatus", "Admin", new {Model.ReturnUrl}, FormMethod.Post, true, new {@class = "d-flex"}))
            {
                @Html.Hidden("OrderId", Model.Order.Id)
                @Html.Hidden("Status", OrderStatus.Completed)
                <input class="btn btn-turquoise mx-2" type="submit" value="Отметить как завершённый"/>
            }
        }
    </section>
</section>