Ugugushka.WebUI/ViewModels/AddToyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using CloudinaryDotNet;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using Ugugushka.Domain.DtoModels;
using Ugugushka.WebUI.Code.Abstractions;

namespace Ugugushka.WebUI.ViewModels
{
    public class AddToyViewModel : AbstractCloudinaryModel
    {
        public AddToyViewModel() : base(null) { }
        public AddToyViewModel(Cloudinary cloudinary) : base(cloudinary) { }

        public int Id { get; set; }

        [DisplayName("Название")]
        [MaxLength(70, ErrorMessage = "Количество символов названия не должно превышать 70!")]
        [Required(ErrorMessage = "Вы должны ввести название!")]
        public string Name { get; set; }

        [DisplayName("Описание")]
        [MaxLength(500, ErrorMessage = "Количество символов описания не должно превышать 500!")]
        [Required(ErrorMessage = "Вы должны ввести описание")]
        public string Description { get; set; }

        [DisplayName("Категория")] 
        public int? CategoryId { get; set; }

        [DisplayName("Цена")]
        [Required(ErrorMessage = "Вы должны ввести цену!")]
        [DataType(DataType.Currency, ErrorMessage = "Некорректное значение")]
        [Range(0, Double.MaxValue, ErrorMessage = "Цена должна быть больше 0!")]
        public decimal Price { get; set; }

        [MinLength(1, ErrorMessage = "Нужно добавить как минимум 1 фотографию!")]
        [MaxLength(5, ErrorMessage = "Максимально возможное количество фотографий - 5!")]
        public List<ToyImageDto> Images { get; set; } = new List<ToyImageDto>();
    }
}

Ugugushka.WebUI/Controllers/ImageController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Ugugushka.Domain.Code.Constants;
using Ugugushka.Domain.Code.Interfaces;

namespace Ugugushka.WebUI.Controllers
{
    [Authorize(Roles = RoleDefaults.Admin)]
    [ApiController]
    [Route("api/[controller]")]
    public class ImageController : Controller
    {
        private readonly IPictureManager _pictureManager;
        public ImageController(IPictureManager pictureManager)
        {
            _pictureManager = pictureManager;
        }

        [HttpPost]
        public async Task<IActionResult> UploadImages(IFormFileCollection images)
        {
            if (images == null)
                return BadRequest();

            return Ok(await _pictureManager.UploadPicturesAsync(images));
        }
    }
}

Ugugushka.WebUI/Controllers/ToyController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Ugugushka.Common.Concretes;
using Ugugushka.Domain.Code.Constants;
using Ugugushka.Domain.Code.Extensions;
using Ugugushka.Domain.Code.Interfaces;
using Ugugushka.Domain.DtoModels;
using Ugugushka.WebUI.Code.Abstractions;
using Ugugushka.WebUI.ViewModels;

namespace Ugugushka.WebUI.Controllers
{
    [Authorize]
    public class ToyController : AbstractController
    {
        private const int ToysPageSize = 10;

        private readonly IToyManager _toyManager;
        private readonly IPictureManager _pictureManager;

        public ToyController(IToyManager toyManager, IPictureManager pictureManager, IMapper mapper) : base(mapper)
        {
            _pictureManager = pictureManager;
            _toyManager = toyManager;
        }

        public async Task<IActionResult> Toys([FromQuery] ToyFilterInfo toyFilter, [FromRoute] int page = 1)
        {
            return View(
                (await _toyManager.GetPagedFilteredAsync(toyFilter,
                    new PageInfo {PageNumber = page, PageSize = ToysPageSize})).Map<ToyDto, ToyItemViewModel>(Mapper));
        }

        [HttpGet]
        [Authorize(Roles = RoleDefaults.Admin)]
        public IActionResult AddToy() =>
            View(new AddToyViewModel(_pictureManager.Cloudinary));

        [HttpPost]
        [Authorize(Roles = RoleDefaults.Admin)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToy(AddToyViewModel toy)
        {
            if (ModelState.IsValid)
            {
                var createdToy = await _toyManager.CreateAsync(Mapper.Map<AddToyViewModel, ToyCreateDto>(toy));
                
                await _pictureManager.ChangePictureTagAsync(
                    createdToy.Images.Select(x => x.PublicId).ToList(),
                    CloudinaryTagDefaults.Toy);
                await _pictureManager.DeleteTemporaryPicturesAsync();
                
                TempData["message"] = $"{toy.Name} has been saved";
                return RedirectToAction("Toys");
            }
            else
            {
                toy.Cloudinary = _pictureManager.Cloudinary;
                return View(toy);
            }
        }

        public async Task<IActionResult> ToyInfo([FromRoute] int id) =>
            View(new ToyInfoViewModel(_pictureManager.Cloudinary) {Toy = await _toyManager.GetByIdAsync(id)});

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            await _toyManager.DeleteAsync(id);

            return RedirectToAction("Toys");
        }
    }
}

Ugugushka.WebUI/Views/Toy/AddToy.cshtml
@model AddToyViewModel
@{
    ViewBag.Title = "Управление - Добавить товар";
}

@section Css
{
    <link rel="stylesheet" href="~/css/loader.css"/>
}

<div class="my-5">
        <h2>Добавить товар</h2>
        @using (Html.BeginForm("AddToy", "Toy", FormMethod.Post, htmlAttributes: new { @enctype = "multipart/form-data", @id = "form" }))
        {
            @Html.HiddenFor(x => x.Id)
            @foreach (var property in ViewData.ModelMetadata.Properties)
            {
                if (property.PropertyName != "Id" && 
                    property.PropertyName != "Images" && 
                    property.PropertyName != "Cloudinary")
                {
                    <div class="form-group">
                        <label class="d-block mb-3" for="@property.PropertyName">@(property.DisplayName ?? property.PropertyName)</label>
                        @if (property.PropertyName == "Description")
                        {
                            @Html.TextArea(property.PropertyName, null, new { rows = 5, @class = "form-control text-input", @placeholder = property.DisplayName })
                        }
                        else if (property.PropertyName == "IsOnStock")
                        {
                            @Html.CheckBox(property.PropertyName)
                        }
                        else
                        {
                            @Html.TextBox(property.PropertyName, null, htmlAttributes: new { @class = "form-control text-input", @placeholder = property.DisplayName })
                        }
                        @Html.ValidationMessage(property.PropertyName)
                    </div>
                }
            }

            <div class="form-group">
                <label class="d-block mb-3">Фотографии</label>
                <div class="d-flex align-items-center">
                    <div class="d-flex" id="images"></div>
                    <label id="upload_btn" class="d-flex btn-upload-img" for="image">
                        <div id="plus_icon" class="d-flex upload-icon justify-content-center align-items-center">
                            <i class="fas fa-plus"></i>
                        </div>
                        <div id="loader" class="d-flex loader">
                            <div class="dot"></div>
                            <div class="dot"></div>
                            <div class="dot"></div>
                        </div>
                    </label>
                    <input hidden type="file" name="image" id="image" />
                </div>
                @Html.ValidationMessageFor(x => x.Images)
            </div>

            <input type="submit" class="btn btn-primary" value="Сохранить" />
            @Html.ActionLink("Назад", "Toys", null, htmlAttributes: new { @class = "btn btn-primary" })

            <div id="img_data"></div>
        }
    </div>

@section PageScripts
{
    <script src="~/libs/jquery/jquery.min.js" type="text/javascript"></script>
    <script src="~/libs/jquery-validate/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/libs/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script>
        // Razor JS variables initialization
        const cloudPath = '@Model.Cloudinary.Api.UrlImgUp.BuildUrl()';
        var imgArray = [
            @foreach (var img in Model.Images)
            {
                @: { publicId: '@img.PublicId', format: '@img.Format' },
            }
        ];
        var isUploadBtnHided = false;

        // DOM Elements
        const imgInputBlock = $('#img_data');
        const imgBlock = $("#images");
        const loader = $("#loader");
        const plusIcon = $("#plus_icon");
        const uploadBtn = $("#upload_btn");

        $(document).ready(function() {
            updateImageArray();
            updateInputArray();
            loader.toggle();
            loader.toggleClass('d-flex');
        });

        $("#image").on("change",
            function(e) {
                uploadImage();
            });

        function toggleUploading() {
            loader.toggle();
            loader.toggleClass('d-flex');
            plusIcon.toggle();
            plusIcon.toggleClass('d-flex');
        }

        function updateUploadBtn() {
            if (imgArray.length === 5 && !isUploadBtnHided) {
                uploadBtn.toggleClass('d-flex');
                uploadBtn.toggleClass('collapse');
                isUploadBtnHided = !isUploadBtnHided;
            } else if(imgArray.length < 5 && isUploadBtnHided) {
                uploadBtn.toggleClass('d-flex');
                uploadBtn.toggleClass('collapse');
                isUploadBtnHided = !isUploadBtnHided;
            }
        }

        function updateInputArray() {
            // Update input array
            imgInputBlock.html('');
            imgArray.forEach(function(item, index) {
                appendImageInput(item.publicId, item.format, index);
            });
        }

        function updateImageArray() {
            imgBlock.html('');
            imgArray.forEach(function(item, index) {
                appendImage(item.publicId, item.format, index);
            });
        }

        function appendImage(publicId, format, index) {
            $("<img class='d-flex mr-2' height='150' width='150'/>")
                .attr('src', `${cloudPath}/${publicId}.${format}`)
                .attr('data-index', index)
                .on('click', deleteImage)
                .appendTo(imgBlock);
        }

        function appendImageInput(publicId, format, index) {
            $(`<input type='hidden' name='Images[${index}].Format' id='Images[${index}]_Format'/>`)
                .val(format)
                .appendTo(imgInputBlock);
            $(`<input type='hidden' name='Images[${index}].PublicId' id='Images[${index}]_PublicId'/>`)
                .val(publicId)
                .appendTo(imgInputBlock);
        }

        function deleteImage(e) {
            e.target.remove();
            imgArray.splice(e.target.dataset.index, 1);
            updateInputArray();
            updateUploadBtn();
        }

        $('img.load-preview').on('click', deleteImage);

        function uploadImage() {
            var files = $("#image")[0].files;
            if (files) {
                toggleUploading();
                const form = new FormData();
                form.append("image", files[0]);

                fetch('@Url.Action("UploadImages", "Image")',
                        {
                            method: 'POST',
                            body: form
                        })
                    .then(r => {
                        r.json().then(r => {
                            appendImage(r.publicId, r.format, imgArray.length);
                            appendImageInput(r.publicId, r.format, imgArray.length);
                            imgArray.push({ publicId: r.publicId, format: r.format });
                            toggleUploading();
                            updateUploadBtn();
                        });
                    });
            }
        }
    </script>
}

Ugugushka.WebUI/Views/Toy/Toys.cshtml
@using Ugugushka.WebUI.HtmlHelpers
@model IPagedResult<ToyItemViewModel>
@{
    ViewBag.Title = "Управление - Игрушки";
}

<div class="mt-5">
    @if (TempData["message"] != null)
    {
        <div>
            @TempData["message"]
        </div>
    }
    <h2>Игрушки (@Model.TotalItems)</h2>
    <a class="btn btn-primary" href="@Url.Action("AddToy", "Toy")">Добавить</a>
    <table class="table mt-3">
        <thead>
        <tr>
            <th>Ид</th>
            <th>Название</th>
            <th>Описание</th>
            <th>Категория</th>
            <th>Раздел</th>
            <th>Цена</th>
            <th>На складе</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var toy in Model.Items)
        {
            <tr>
                <td>@toy.Id</td>
                <td>@toy.Name</td>
                <td>@toy.Description</td>
                <td>@Html.DefaultString(toy.CategoryName, "Нет")</td>
                <td>@Html.DefaultString(toy.PartitionName, "Нет")</td>
                <td>@toy.Price</td>
                <td>@Html.IsOnStock(toy.IsOnStock)</td>
                <td>
                    @using (Html.BeginForm("Delete", "Toy"))
                    {
                        @Html.Hidden("Id", toy.Id)
                        <input type="submit" value="Удалить"/>
                    }
                </td>
            </tr>
        }
        </tbody>
    </table>

    <div class="d-flex align-self-center mt-3">
        @Html.PageLinks(@Model.PageNumber, @Model.TotalPages, x => Url.Action("Toys", new {page = x}))
    </div>
</div>